// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/locations": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Расположение"
                ],
                "summary": "Список расположений камер",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Location"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ActionError"
                        }
                    }
                }
            }
        },
        "/scan": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Сканирование"
                ],
                "summary": "Добавить отсканированный номер",
                "parameters": [
                    {
                        "description": "Добавить сканирование",
                        "name": "scan",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.AddScanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Scan"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ActionError"
                        }
                    }
                }
            }
        },
        "/vin": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Распознание"
                ],
                "summary": "Распознать vin и другие данные по госномеру",
                "parameters": [
                    {
                        "description": "Распознать по госномеру",
                        "name": "vin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.VinByPlateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Vin"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ActionError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ActionError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "User not found"
                },
                "url": {
                    "type": "string",
                    "example": "scan.e92.ru/api/v1/scan"
                }
            }
        },
        "controller.AddScanRequest": {
            "type": "object",
            "required": [
                "place",
                "plate",
                "scanned_at"
            ],
            "properties": {
                "place": {
                    "type": "string",
                    "example": "pokrovka"
                },
                "plate": {
                    "type": "string",
                    "example": "M343TT123"
                },
                "scanned_at": {
                    "type": "string",
                    "example": "2022-07-23 11:23:55"
                }
            }
        },
        "controller.VinByPlateRequest": {
            "type": "object",
            "required": [
                "plate"
            ],
            "properties": {
                "plate": {
                    "type": "string",
                    "example": "M343TT123"
                }
            }
        },
        "model.Location": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "pokrovka"
                },
                "id": {
                    "type": "integer",
                    "example": 12
                },
                "name": {
                    "type": "string",
                    "example": "Красноярск Покровка"
                }
            }
        },
        "model.Scan": {
            "type": "object",
            "required": [
                "location_id",
                "plate",
                "scanned_at",
                "user_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2022-08-04T12:23:52.372+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 76352
                },
                "location_id": {
                    "type": "integer",
                    "example": 12
                },
                "plate": {
                    "type": "string",
                    "example": "О245КМ142"
                },
                "scanned_at": {
                    "type": "string",
                    "example": "2022-07-29T11:23:55+07:00"
                },
                "user_id": {
                    "type": "integer",
                    "example": 234
                }
            }
        },
        "model.Vin": {
            "type": "object",
            "required": [
                "author_user_id",
                "plate",
                "status_id"
            ],
            "properties": {
                "author_user_id": {
                    "type": "integer",
                    "example": 234
                },
                "body": {
                    "type": "string",
                    "example": "KGC100005240"
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-07-28T11:23:55+07:00"
                },
                "id": {
                    "type": "integer",
                    "example": 7635
                },
                "mark_id": {
                    "type": "integer",
                    "example": 23
                },
                "model_id": {
                    "type": "integer",
                    "example": 231
                },
                "plate": {
                    "type": "string",
                    "example": "О245КМ142"
                },
                "response": {
                    "type": "string",
                    "example": "{...}"
                },
                "response_error": {
                    "type": "string",
                    "example": "400"
                },
                "status_id": {
                    "type": "integer",
                    "example": 3
                },
                "updated_at": {
                    "type": "string",
                    "example": "2022-07-23T11:23:55+07:00"
                },
                "vin": {
                    "type": "string",
                    "example": "XTA219170K0330071"
                },
                "vin2": {
                    "type": "string",
                    "example": "XTA219170K0330071"
                },
                "year": {
                    "type": "integer",
                    "example": 2012
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Дискаунтер автозачастей е92",
	Description:      "Здесь представлены все методы для работы админстраторов и менеджеров магазинов.\nВопросы на info@e92.ru.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
